---
- name: Install Unbound
  ansible.builtin.apt:
    name: unbound
    state: present
    update_cache: yes
  become: true

- name: Ensure Unbound config directory exists
  ansible.builtin.file:
    path: "{{ unbound_config_path | dirname }}"
    state: directory
    mode: "0755"
  become: true

- name: Deploy Unbound homelab config
  ansible.builtin.template:
    src: homelab.conf.j2
    dest: "{{ unbound_config_path }}"
    mode: "0644"
  notify: Restart unbound
  become: true

- name: Ensure unbound service is enabled and running
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: true
  become: true
