---
personal_site_image: "ghcr.io/neodymium6/profile.neodymium6.net:latest"
personal_site_dir: "/opt/stacks/personal-site"
personal_site_compose_path: "{{ personal_site_dir }}/docker-compose.yml"

personal_site_name: "personal-site"
personal_site_port: 8080

personal_site_enable_ufw: true
personal_site_allow_from_proxy_only: true
