---
personal_site_image: "ghcr.io/neodymium6/profile.neodymium6.net:latest"
personal_site_dir: "/opt/stacks/personal-site"
personal_site_compose_path: "{{ personal_site_dir }}/docker-compose.yml"

personal_site_name: "personal-site"
personal_site_backend_ports:
  - 8080
  - 8081

personal_site_enable_ufw: true
personal_site_allow_from_proxy_only: true

# systemd timer: pull and restart periodically
personal_site_update_enable: true
personal_site_update_on_boot_sec: "2m"
personal_site_update_unit_active_sec: "1h"
personal_site_update_cleanup_enable: false
personal_site_update_cleanup_until: "168h"
