---
personal_site_image: "nginx:stable-alpine"
personal_site_dir: "/opt/stacks/personal-site"
personal_site_html_dir: "{{ personal_site_dir }}/html"
personal_site_compose_path: "{{ personal_site_dir }}/docker-compose.yml"

personal_site_name: "personal-site"
personal_site_port: 8080

personal_site_title: "Personal Site"
personal_site_heading: "Personal Site"
personal_site_subtitle: "Deployed by Ansible"

personal_site_enable_ufw: true
personal_site_allow_from_proxy_only: true
