---
homepage_image: "ghcr.io/gethomepage/homepage:latest"
homepage_dir: "/opt/stacks/homepage"
homepage_config_dir: "{{ homepage_dir }}/config"
homepage_compose_path: "{{ homepage_dir }}/docker-compose.yml"

homepage_port: 3000

homepage_enable_ufw: true
homepage_allow_from_proxy_only: true
