---
prometheus_image: "prom/prometheus:v2.49.0"
prometheus_dir: "/opt/stacks/prometheus"
prometheus_config_dir: "{{ prometheus_dir }}/config"
prometheus_data_dir: "{{ prometheus_dir }}/data"
prometheus_compose_path: "{{ prometheus_dir }}/docker-compose.yml"
prometheus_config_path: "{{ prometheus_config_dir }}/prometheus.yml"
prometheus_port: 9090
prometheus_service_name: "prometheus"
prometheus_enable_ufw: true
prometheus_allow_from_proxy_only: true
prometheus_alertmanager_targets: []
