---
grafana_image: "grafana/grafana:10.3.0"
grafana_dir: "/opt/stacks/grafana"
grafana_config_dir: "{{ grafana_dir }}/config"
grafana_data_dir: "{{ grafana_dir }}/data"
grafana_compose_path: "{{ grafana_dir }}/docker-compose.yml"
grafana_port: 3001
grafana_service_name: "grafana"
grafana_enable_ufw: true
grafana_allow_from_proxy_only: true
